"""Manual seed dataset: realistic Indian market snapshots (illustrative)."""

SEED_CARS: list[dict] = [
    {"brand": "Maruti Suzuki", "model": "Swift", "price_lakh": 7.5, "mileage": 23.2, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 2, "engine_cc": 1197},
    {"brand": "Maruti Suzuki", "model": "Dzire", "price_lakh": 8.2, "mileage": 22.4, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Sedan", "safety_rating": 2, "engine_cc": 1197},
    {"brand": "Maruti Suzuki", "model": "Baleno", "price_lakh": 8.9, "mileage": 22.9, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 3, "engine_cc": 1197},
    {"brand": "Maruti Suzuki", "model": "Brezza", "price_lakh": 10.5, "mileage": 19.8, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 4, "engine_cc": 1462},
    {"brand": "Maruti Suzuki", "model": "Grand Vitara", "price_lakh": 14.2, "mileage": 21.1, "fuel_type": "Hybrid", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1462},
    {"brand": "Maruti Suzuki", "model": "Ertiga", "price_lakh": 11.3, "mileage": 20.5, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "MUV", "safety_rating": 4, "engine_cc": 1462},
    {"brand": "Hyundai", "model": "i20", "price_lakh": 8.5, "mileage": 21.0, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 3, "engine_cc": 1197},
    {"brand": "Hyundai", "model": "Venue", "price_lakh": 10.8, "mileage": 18.7, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 4, "engine_cc": 998},
    {"brand": "Hyundai", "model": "Creta", "price_lakh": 14.9, "mileage": 17.4, "fuel_type": "Petrol", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1497},
    {"brand": "Hyundai", "model": "Verna", "price_lakh": 13.2, "mileage": 18.6, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Sedan", "safety_rating": 5, "engine_cc": 1482},
    {"brand": "Hyundai", "model": "Tucson", "price_lakh": 31.5, "mileage": 12.9, "fuel_type": "Diesel", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1997},
    {"brand": "Tata", "model": "Tiago", "price_lakh": 6.8, "mileage": 20.0, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 4, "engine_cc": 1199},
    {"brand": "Tata", "model": "Altroz", "price_lakh": 8.9, "mileage": 19.0, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 5, "engine_cc": 1199},
    {"brand": "Tata", "model": "Punch", "price_lakh": 8.2, "mileage": 18.8, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1199},
    {"brand": "Tata", "model": "Nexon", "price_lakh": 11.5, "mileage": 17.4, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1199},
    {"brand": "Tata", "model": "Harrier", "price_lakh": 19.8, "mileage": 16.8, "fuel_type": "Diesel", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1956},
    {"brand": "Tata", "model": "Safari", "price_lakh": 21.4, "mileage": 16.1, "fuel_type": "Diesel", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1956},
    {"brand": "Mahindra", "model": "XUV700", "price_lakh": 22.5, "mileage": 14.5, "fuel_type": "Diesel", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 2198},
    {"brand": "Mahindra", "model": "Scorpio N", "price_lakh": 17.9, "mileage": 15.2, "fuel_type": "Diesel", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 2184},
    {"brand": "Mahindra", "model": "Thar", "price_lakh": 15.5, "mileage": 15.2, "fuel_type": "Diesel", "transmission": "Manual", "body_type": "SUV", "safety_rating": 4, "engine_cc": 2184},
    {"brand": "Mahindra", "model": "Bolero Neo", "price_lakh": 11.2, "mileage": 17.2, "fuel_type": "Diesel", "transmission": "Manual", "body_type": "SUV", "safety_rating": 3, "engine_cc": 1493},
    {"brand": "Mahindra", "model": "XUV300", "price_lakh": 10.9, "mileage": 17.0, "fuel_type": "Diesel", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1497},
    {"brand": "Honda", "model": "Amaze", "price_lakh": 8.7, "mileage": 18.6, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Sedan", "safety_rating": 4, "engine_cc": 1199},
    {"brand": "Honda", "model": "City", "price_lakh": 13.8, "mileage": 17.8, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Sedan", "safety_rating": 5, "engine_cc": 1498},
    {"brand": "Honda", "model": "Elevate", "price_lakh": 14.5, "mileage": 16.6, "fuel_type": "Petrol", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1498},
    {"brand": "Toyota", "model": "Glanza", "price_lakh": 9.5, "mileage": 22.3, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 4, "engine_cc": 1197},
    {"brand": "Toyota", "model": "Urban Cruiser Hyryder", "price_lakh": 16.8, "mileage": 21.1, "fuel_type": "Hybrid", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1467},
    {"brand": "Toyota", "model": "Innova Crysta", "price_lakh": 22.0, "mileage": 12.0, "fuel_type": "Diesel", "transmission": "Manual", "body_type": "MUV", "safety_rating": 5, "engine_cc": 2393},
    {"brand": "Toyota", "model": "Fortuner", "price_lakh": 38.5, "mileage": 10.0, "fuel_type": "Diesel", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 2755},
    {"brand": "Kia", "model": "Sonet", "price_lakh": 10.2, "mileage": 18.4, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1199},
    {"brand": "Kia", "model": "Seltos", "price_lakh": 13.9, "mileage": 17.0, "fuel_type": "Petrol", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1497},
    {"brand": "Kia", "model": "Carens", "price_lakh": 14.2, "mileage": 16.5, "fuel_type": "Diesel", "transmission": "Manual", "body_type": "MUV", "safety_rating": 5, "engine_cc": 1493},
    {"brand": "Skoda", "model": "Slavia", "price_lakh": 13.5, "mileage": 18.7, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Sedan", "safety_rating": 5, "engine_cc": 999},
    {"brand": "Skoda", "model": "Kushaq", "price_lakh": 14.8, "mileage": 17.8, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 999},
    {"brand": "Volkswagen", "model": "Virtus", "price_lakh": 13.9, "mileage": 18.6, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Sedan", "safety_rating": 5, "engine_cc": 999},
    {"brand": "Volkswagen", "model": "Taigun", "price_lakh": 14.6, "mileage": 17.5, "fuel_type": "Petrol", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1498},
    {"brand": "MG", "model": "Hector", "price_lakh": 17.5, "mileage": 14.5, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1451},
    {"brand": "MG", "model": "Astor", "price_lakh": 12.9, "mileage": 14.0, "fuel_type": "Petrol", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 1498},
    {"brand": "Citroën", "model": "C3", "price_lakh": 7.9, "mileage": 19.4, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 4, "engine_cc": 1199},
    {"brand": "Citroën", "model": "C3 Aircross", "price_lakh": 11.8, "mileage": 18.5, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 4, "engine_cc": 1199},
    {"brand": "Renault", "model": "Kiger", "price_lakh": 8.4, "mileage": 19.0, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 4, "engine_cc": 999},
    {"brand": "Renault", "model": "Triber", "price_lakh": 9.1, "mileage": 19.0, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "MUV", "safety_rating": 4, "engine_cc": 999},
    {"brand": "Nissan", "model": "Magnite", "price_lakh": 9.8, "mileage": 18.8, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 4, "engine_cc": 999},
    {"brand": "Maruti Suzuki", "model": "XL6", "price_lakh": 14.5, "mileage": 19.0, "fuel_type": "Petrol", "transmission": "Automatic", "body_type": "MUV", "safety_rating": 4, "engine_cc": 1462},
    {"brand": "Hyundai", "model": "Exter", "price_lakh": 9.2, "mileage": 19.2, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "SUV", "safety_rating": 4, "engine_cc": 1197},
    {"brand": "Tata", "model": "Tigor", "price_lakh": 7.9, "mileage": 19.2, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Sedan", "safety_rating": 4, "engine_cc": 1199},
    {"brand": "Maruti Suzuki", "model": "Wagon R", "price_lakh": 6.5, "mileage": 24.4, "fuel_type": "Petrol", "transmission": "Manual", "body_type": "Hatchback", "safety_rating": 2, "engine_cc": 998},
    {"brand": "Mahindra", "model": "XUV400 EV", "price_lakh": 18.9, "mileage": 23.0, "fuel_type": "Electric", "transmission": "Automatic", "body_type": "SUV", "safety_rating": 5, "engine_cc": 0},
]
